apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
      version: "9.5.0"
  interval: 5m
  values:
    adminUser: 
    adminPassword: 
    grafana.ini:
      server:
        root_url: "%(protocol)s://%(domain)s/grafana"
    grafana:
      allow_org_create: true
    persistence:
      enabled: true
      size: 10Gi
