apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../../../../../external/flux2-monitoring-example/monitoring/controllers/kube-prometheus-stack/namespace.yaml
configMapGenerator:
  - name: central-grafana-dashboards
    files:
      - control-plane.json
      - cluster.json
      - logs.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled
