apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - mscqa-datasources.yaml
  - mscqa-teams.yaml
  - mscqa-folders.yaml
  - mscqa-folder-permissions.yaml
  - mscqa-grafana-provisioning.yaml
